### ISSUE TITLE
The Light style does not change to the Regular style when the bold effect is applied

### ISSUE THREAD

**Issue by joaopaulo1511** [EbenSorkin/Merriweather-Sans#16]
Hi @EbenSorkin,

I know the Merriweather Sans repository location changed to https://github.com/SorkinType/Merriweather-Sans, but I could not add a new issue there, so I am adding here:

After installing the fonts (static or variable), when creating a new document (on LibreOffice 6.4.6 or on Word Mobile on Windows 10) and formating text with Merriweather Sans Light style, then applying the bold effect, the style is not changed to Merriweather Sans Regular (which would be the bold version of light), but to a faux Merriweather Sans Light "bold" style.

You can test it by typing a line of text, then copying it to a new paragraph, and formatting the first line with the Light style and applying the bold effect (press the B button on the toolbar), then formatting the second line with the Regular style so you can see the letter styles are not equal as they should be.

Is this a problem with the fonts style-linking or is it a problem with the text processors / operating system (Windows) used?

Thanks for this great typeface,

João Paulo

**Comment by EbenSorkin** [comment]
Thanks for letting me know! 

There is a new version of this font family that Type Network mastered which should drop fairly soon now. I am not sure if this behavior will change in that version but it may. I didn't work on it. 

I should also that there is a surprising variety of options and opinions about what should happen when you press a bold button. (Unlike the italic button which is intellectually simpler.)

1) One group thinks that whatever you have in style terms regular, light, black etc pressing the B button should give you the bold style. I think of this as the Bold=Bold camp.

2) Some people think that whatever you have should just get bolder. I can see that you belong to this group at the moment. So perhaps Book becomes Regular, Bold becomes Black, and so on. Or in smaller jumps, Bold becomes Extra Bold ( not black) and Medium becomes Semi bold not Bold. Black just stays black I guess... or is made artificially bolder? IDK In any event, I think of this as the Bold = Bolder camp. I should note that this was fashionable for a while but it isn't used much now because of logical problems inherent and because it is a LOT of labor to make and test.

3) Some people think that the bold button should just make Regular changes to Bold. All other styles have to picked manually from a menu.

I can't say that any of these is satisfying. All of this is the result of Apple and MS having office app suites and deciding that they should include the now-classic four styles R,I,B,BI - which is called Ribbi by type designers. The thing is this was stupid. What people actually would benefit from is Regular, Medium, Bold, Italic, and Small caps. But that's a rant.

I mention all this to say that the question of what should happen is sadly not something that seems to be widely agreed on. I should also say that no matter what behavior the type designer puts in there is a real possibility that the app that uses the font will override that work. This is why the lowest effort solution seems to prevail now.

That's my understanding of the issue at this time.

I wish I could offer something more satisfying! 

Best wishes

**Comment by joaopaulo1511** [comment]
I agree that showing only Ribbi on the selection box is not very smart from Apple and Microsoft, as there should be all the variants there (and then unclutter the font selection menu, which should have only the family name there).

Thanks for the answer,

Best regards and again thank you for this typeface!
