### ISSUE TITLE
Adding Vietnamese

### ISSUE THREAD

**Issue by crystaltype** [EbenSorkin/Merriweather-Sans#7]
I see that this type doesn't have Vietnamese yet.

I'm willing to contribute the complete Vietnamese character set directly, by sending you a 'vietnamese only' glyphapp file for you to review and integrate.

Or, you can make changes and then push your work to master and I will give further feedback :)

**Comment by EbenSorkin** [comment]
There is a version with Vietnamese here

https://github.com/EbenSorkin/Merriweather

If you download the whole thing you will see it. Some of it isn't right yet
because Vietnamese requires a new technical approach to the vertical
metrics. Until I see what the result of this week's experiment I won't know
how much freedom I have to do this part properly.

I hope to push a new one as a formal release here soon:

https://github.com/EbenSorkin/Merriweather/releases

-e.

**Comment by davelab6** [comment]
This is the Sans,tho

**Comment by EbenSorkin** [comment]
oh!

That is being added *now*. So it is coming.

Sorry for the confusion!

-e.

**Comment by EbenSorkin** [comment]
This has been added. See:

https://github.com/SorkinType/Merriweather-Sans/commit/2b53cbf652f34b70c38aad6a184b0f371f4ce3af
